# Generated by Django 5.0.2 on 2024-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STACK_APP', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='COURSES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('offer_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
