# Generated by Django 5.0.2 on 2024-04-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0004_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABOUT_US",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FEATURES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("content", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="INSTRUCTORS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fb_link", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "twitter_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("insta_link", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="testimonial",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
