# Generated by Django 5.0.2 on 2024-05-01 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0005_about_us_features_instructors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="offer_rate",
        ),
    ]
