# Generated by Django 5.0.2 on 2024-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0007_alter_about_us_content_alter_features_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructors",
            old_name="fb_link",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="instructors",
            name="insta_link",
        ),
        migrations.RemoveField(
            model_name="instructors",
            name="twitter_link",
        ),
        migrations.AddField(
            model_name="instructors",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="instructors",
            name="phone",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
