# Generated by Django 5.0.2 on 2024-05-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0008_rename_fb_link_instructors_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
