# Generated by Django 5.0.2 on 2024-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0009_alter_blog_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CONTACT_US",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
