# Generated by Django 5.0.2 on 2024-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0010_contact_us"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact_us",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="contact_us",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
