# Generated by Django 5.0.2 on 2024-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0011_contact_us_date_contact_us_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact_us",
            name="status",
            field=models.IntegerField(
                blank=True, choices=[(1, "Read"), (0, "Unread")], default=0, null=True
            ),
        ),
    ]
