# Generated by Django 5.0.2 on 2024-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STACK_APP", "0012_alter_contact_us_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
